[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
board_build.psram = enabled
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    https://github.com/Seeed-Projects/Seeed_GxEPD2.git
    adafruit/Adafruit GFX Library@^1.11.9
    bblanchon/ArduinoJson@^7.0.4

[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
